### ISSUE TITLE
Remove automatic viewpoint adjustment

### ISSUE THREAD

**Issue by mayacakmak** [hcrlab/stretch_web_interface#1]
Hello Robot's default interface moves the robot's head camera to a preset pose in the Drive and Arm tabs, but maintains the current view in the Hand tab. While the preset poses are useful, sometimes they require a lot of back and forth between the Look view and other tabs. Instead of automatically moving to the preset we want to make the preset pose optional (an additional click once you get to the tab).

**Comment by mayacakmak** [comment]
There are two sides to the code: `robot/` (interfaced directly with ROS) and `operator/` (front end user interface that talks to the robot side over the web). Let's call them back-end and front-end. There is some shared API under `shared/`.

We should be able to address this issue by modifying the `robotModeOn` function in `robot/ros_connect.js` OR just not calling the function when a `mode` command is received (since changing the view is all the function appears to be doing; any other change is in the front-end) OR just not sending the command from the front-end to the back-end in the first place. I think I'll go with the first option (least amount of change in how things work, just in case I'm missing something) though the advantage of the last option would be that the user could have control of the behavior from the front-end.

**Comment by mayacakmak** [comment]
Instead of just removing the code, I'll add a on/off switch in the back-end interface (robot.html) so we can revert this. If this works it could be a way to configure/customize the interface behavior before a study, without changing code.

**Comment by mayacakmak** [comment]
Changed my mind about having a flag for automatic camera view change in the back-end because it doesn't allow for reusing back-end <-> frontend communication functionality that is already in place (i.e. would require setting up a separate command for view changes). I'm more confident now that a mode change has no other meaning for the back-end than the view change so will treat the mode change as a view change. We can add more preset views to the back end (currently only three for Drive, Arm1, Arm2).

**Comment by mayacakmak** [comment]
Added a button below the camera view "Center camera for current mode" which will manually trigger the view change.

**Comment by mayacakmak** [comment]
Just pushed all the changes for this issue. Needs to be tested.

**Comment by csemecu** [comment]
There were issues with moving the buttons around the video so I'm basically switching it back. At this moment, the changing tabs without automatic camera actions work. Then when you press the button "center camera..." the camera moves to the corresponding preset position.
What doesn't work is the buttons with variable speed. When you click on any of the options "Smallest","Small",.... the console shows back: Invalid velocity: [value] and points to commands.js: 9:13
The problem with the variable speed selection also messes with the messages sent in the moving functions like lookUp, moveForward, liftDown, etc. The var cmd appears to be incomplete and the message is not published in the topic /stretch_controller/follow_joint_trajectory/goal (I tried echoing and pressing on the different sections)
Also, it looks like the only defined values for modifier in the command messages (speeds) is only "small" and "medium"

**Comment by mayacakmak** [comment]
@csemecu did you pull the latest version? I moved the screen regions so all the buttons can be at the bottom.

**Comment by mayacakmak** [comment]
Hmm.. the modifier issue might be related to the functions that actually don't require a modifier. Let me check.

Note that the current code is not using the 'executeCommandBySize' anymore for those functions that have five speeds.

**Comment by mayacakmak** [comment]
Ah okay that was just a simple bug, replaced `if (newV in Object.keys(modifiers))` with `if (Object.keys(modifiers).includes(newV))`. Pull and try again!

**Comment by csemecu** [comment]
The bug that you found helped and now the functions Drive, Arm, and Look work for all the areas of the image. The Hand tab still does not turn the wrist in or out. I imagine that command may not have the modifier. Also, the "smallest" speed still does not work and there are no messages sent when that option is selected.
I still think that even though the other 4 options can be selected, they are making no change in the delta that the robot uses to move. I suspect there might be something hard coded. See https://github.com/hello-robot/stretch_web_interface/blob/5c5e05035f5706c127fb184370fe370bcf9a7815/robot/ros_connect.js#L244

**Comment by mayacakmak** [comment]
Hmm, I see, it might be that the parameters to the lower level functions are being ignored.

For the smallest speed, any error messages?

Hand tab not working is odd, again no errors?

**Comment by mayacakmak** [comment]
Yea, it looks like only headTilt and headPan do something about the parameter passed.. all the other functions just look at the sign and ignore the value. That means we cannot even trust what those values mean, we would need to go off of what is being sent in the ROS commands.

**Comment by mayacakmak** [comment]
Okay, what I'll try to do is move the speed adjustment stuff into ros_connect instead of commands. This should take 10-20 minutes.

**Comment by mayacakmak** [comment]
@csemecu Just pushed a version that attempts to modify low level commands based on speed setting.

**Comment by csemecu** [comment]
The newest version does address everything with the variable speeds. We tried the base and the arm and the difference is notable. One little bug that seems to be around is driving forward sends the base backwards. Another thing that is still an issue, is that the wrist is not moving in or out. There was an error message in the roslaunch terminal:

> [INFO] [1600922853.423826]: /stretch_driver joint_traj action: New trajectory received with joint_names = ['joint_gripper_finger_left']
> [ERROR] [1600922853.560348]: Exception in your execute callback: list index out of range
> Traceback (most recent call last):
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
>     self.execute_callback(goal)
>   File "/home/hello-robot/catkin_ws/src/stretch_ros/stretch_core/nodes/joint_trajectory_server.py", line 116, in execute_cb
>     for c in command_groups]
>   File "/home/hello-robot/catkin_ws/src/stretch_ros/stretch_core/nodes/command_groups.py", line 314, in init_execution
>     a_r=self.goal['acceleration'])
>   File "/home/hello-robot/.local/lib/python2.7/site-packages/stretch_body/end_of_arm.py", line 41, in move_by
>     self.motors[joint].move_by(x_r, v_r, a_r)
>   File "/home/hello-robot/.local/lib/python2.7/site-packages/stretch_body/stretch_gripper.py", line 50, in move_by
>     self.pull_status() #Ensure up to date
>   File "/home/hello-robot/.local/lib/python2.7/site-packages/stretch_body/stretch_gripper.py", line 56, in pull_status
>     DynamixelHelloXL430.pull_status(self,data)
>   File "/home/hello-robot/.local/lib/python2.7/site-packages/stretch_body/dynamixel_hello_XL430.py", line 73, in pull_status
>     x = self.motor.get_pos()
>   File "/home/hello-robot/.local/lib/python2.7/site-packages/stretch_body/dynamixel_XL430.py", line 293, in get_pos
>     xn, dxl_comm_result, dxl_error= self.read_int32_t(XL430_ADDR_PRESENT_POSITION)
>   File "/home/hello-robot/.local/lib/python2.7/site-packages/stretch_body/dynamixel_XL430.py", line 147, in read_int32_t
>     x, dxl_comm_result, dxl_error = self.packet_handler.read4ByteTxRx(self.port_handler, self.dxl_id, addr)
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/dynamixel_sdk/protocol2_packet_handler.py", line 612, in read4ByteTxRx
>     DXL_MAKEWORD(data[2], data[3])) if (result == COMM_SUCCESS) else 0
> IndexError: list index out of range

**Comment by mayacakmak** [comment]
Nice! Taking a look at these two bugs now:

* Wrist not moving (since the first update)
* Base forward/backward swapped or one of them is wrong?

**Comment by mayacakmak** [comment]
The direction bug was obvious, that should be fixed, though good to test thoroughly to see everything is going in the right direction and nothing was forgotten.

**Comment by mayacakmak** [comment]
Can't figure out the issue with the wrist. It is supposed to move the 'joint_wrist_yaw' joint with the command called from the operator interface, whereas this error is related to the 'joint_gripper_finger_left' joint.. I wonder if it is related or not. Are you able to see console log on the robot side (perhaps on the browser from which you log in and then supposedly displays the camera image)? Is there a message like 'attempting to send wristMove command'?

**Comment by mayacakmak** [comment]
One possible debug info: Does the wrist still work in the original interface?

**Comment by csemecu** [comment]
Yes, we figured the signs, the wrist and the default speed in the html to show medium. If you revert your changes we can push ours that were tested =)

**Comment by mayacakmak** [comment]
Shoot I pushed already, even f I revert it will give you a conflict b/c that's what we both will have changed. You could just pull and let it have conflicts then remove the conflicts manually to be safe.

**Comment by csemecu** [comment]
We can create a different branch. For now, it works

**Comment by mayacakmak** [comment]
Good idea, just push onto another branch so it's backed up. I can merge onto master.

**Comment by mayacakmak** [comment]
We might want to revert this change, depending on other interface choices given that in the study the most common "pattern" was <change mode + center view> :-)
