### ISSUE TITLE
Settings menu/page

### ISSUE THREAD

**Issue by mayacakmak** [hcrlab/stretch_web_interface#15]
We want certain parameters to be exposed to the user as something they can tune themselves or chose amongst options. For this we envision as settings menu accessible through the interface (some type of gear icon on the top right).

![Screen Shot 2021-06-24 at 1 56 41 PM](https://user-images.githubusercontent.com/3083404/123331553-48989500-d4f4-11eb-875c-7d55e744403a.png)

We need to first think about the general way we want to enable this. 
* We probably want the user's setting to be in Firebase so they are remembered. We might want some sort of Javascript global corresponding to each setting variable to be set to the user's preferred value when the connection to the Firebase is first made in the beginning. Setting should be updated whenever the user changes them. 
* Make it programatically easy to add new setting (i.e. should not need to copy paste a bunch of HTML, but instead just call one function with new parameters specifying parameter type and interface type (slider, radio button, text, color picker, etc.)). I have some code from EMAR we could reuse.
* Have some good defaults for each parameter for new users.
* I don't think we want settings to be a separate HTML page, but rather have them overlaid or re-render the page without loosing all the JS context. We could just use [Bootstrap Modal](https://getbootstrap.com/docs/4.0/components/modal/).

This reminds me we now need to switch to having users log in, rather than be anonymous users. Will add a separate issue for that.

Some things to include in settings off the top of my head (keep adding to this thread as we think of them):
* Torque feedback sensitivity
* Continuous action update frequency

@KaviMD let me know what you think about how to implement settings.

**Comment by mayacakmak** [comment]
Address Issue #16 first.

**Comment by mayacakmak** [comment]
I made a rough version of this by hiding away some things on the interface into a Modal overlay that can be opened from a 'settings' button. Will improve later.

<img width="1106" alt="Screen Shot 2021-07-01 at 11 25 11 PM" src="https://user-images.githubusercontent.com/3083404/124230281-9ea4a400-dac3-11eb-9ae3-5cc295f7843e.png">

**Comment by nickswalker** [comment]
Closed with f9c1c9d61ea7d36c074d06069ad260db4a4b2a29.

Some additional controls added in later commits:
![Screenshot from 2022-02-04 11-51-54](https://user-images.githubusercontent.com/924295/152594692-5e54c453-6d14-41b5-aec4-834eb0af257f.png)
