### ISSUE TITLE
Integrate new camera views

### ISSUE THREAD

**Issue by mayacakmak** [hcrlab/stretch_web_interface#29]
New capabilities to include the wide angle head camera and wrist camera views in the interface. Implemented by Charlie in the upstream repo wide_angle_cameras branch--this merge might be tricky so perhaps first take a look at implementation and test it as is before merging.

**Comment by hello-ck** [comment]
The wide-angle branch of the code has changed so much that it's probably going to be more of a reference from which you can manually merge pieces of code. This morning, I was actually thinking about how to manage it. My current guess is that I should move the wide-angle camera branch to a distinct repository with a different name that can be installed alongside stretch_web_interface. Does this sound helpful to you?

**Comment by mayacakmak** [comment]
Currently the two camera images are sent to the operator after being rendered onto a single image. The fisheye interface uses the combined image as is. One approach extending this would be to combine all three (or as many as requested from the operator) images on the robot side and deconstruct them on the operator side to render them in separate parts of the interface. Another approach is to try and send the videos separately--not sure about how to do this yet, but from a quick search, there [might be an approach allowing this](https://webrtccourse.com/course/webrtc-codelab/module/fiddle-of-the-month/lesson/multiple-video-tracks-on-a-single-peer-connection/) (apparently it is a use case that has become important recently in the context of sharing a camera and a screen over video, like in Zoom). Basically it seems to be using multiple tracks for different videos. I'll give this a try.

See email chain titled "new fisheye web interface can be installed at the same time" for more context.

**Comment by mayacakmak** [comment]
Good news! I tried the approach of sending multiple videos through multiple remote tracks (described in the link above) and it worked--I was able to receive three separate video streams on the operator side. Displayed two here for testing with the current interface:

![Screenshot from 2021-07-10 16-33-48](https://user-images.githubusercontent.com/3083404/125209267-7c8ded00-e24c-11eb-8712-cafe3c32cf43.png)

- [ ] We need to figure out which track/stream received on the operator side is which (pantilt, overhead, gripper). I tried changing the `'id` and `label` properties of the track but those were read only; I tried adding a `name` property but that did not work either. Also those things (id and label) are not constant--they're different at every run so cannot hardcode them either. Perpahs something needs to be added to the "description" and sent to the operator.
- [ ] The camera images need to be re-oriented (perhaps provide two different orientations of the overhead camera for driving and manipulation) and zoomed (get rid of the unnecessary black parts; only need the front parts for manipulation). This can be done either on the back end or the front end.
- [ ] Figure out how to display the new camera views--there are many options. Ideally a customizable interface would be most useful--where the user can decide which camera views to include in which mode. 
- [ ] Might want to go back to having modes in different tabs, so we can recreate Charlie's fish-eye interface as it is.
- [ ] Need to provide different overlays for the camera views--different overlay for same camera view in manipulation versus navigation.
- [ ] The "look" buttons should be removed when the view is anything other than the pan-tilt camera.

**Comment by nickswalker** [comment]
Closed with 302ac5d57e5bd4eb4a30b9e4d656e921a715792d through 8236d961040501be2e246bf56ab1251e2a8540b5.

In later versions of the code (5cd48eaa222382103c490a56956142ff68936e73) we moved track name metadata into the signalling channel, where we can ensure it arrives before the remote peer starts using the tracks by sending the information along with the session description ([idea from this Stackoverflow answer](https://stackoverflow.com/a/65412097/1497463)).
