### ISSUE TITLE
Permanent transparent overlay of icons

### ISSUE THREAD

**Issue by mayacakmak** [hcrlab/stretch_web_interface#32]
Henry had asked this a while ago but I thought he did not care as much once he got used to the controls. Now with the new fish eye interface (which has lots of new overlays that are not always easy to guess) he mentioned it again as a request so I'm implementing it--should be pretty simple.

**Comment by nickswalker** [comment]
Closed with d2c0173af2add682f40b56dc5e16ec70c68615aa
