### ISSUE TITLE
Displaying environment maps in the web interface

### ISSUE THREAD

**Issue by kavidey** [hcrlab/stretch_web_interface#37]
[ros2djs ](https://wiki.ros.org/ros2djs/Tutorials/VisualizingAMap) makes it easy to display `.pgm` map files in the web interface. I don't know enough about ROS to know if this is the default/normal way that map file are stored, but this should be pretty easy if it is.

From the web interface, there is no way to select which map is displayed. Instead the map has to be served up from ros:
```bash
rosrun map_server map_server <PATH_TO_MAP_FILE> 0.05
```

Then the web interface should automatically detect and display it.

**Comment by nickswalker** [comment]
Initially added in 21c952a...841a8b1
