### ISSUE TITLE
Show battery information

### ISSUE THREAD

**Issue by nickswalker** [hcrlab/stretch_web_interface#43]
High effort manipulation can cause the robot to reboot when the battery is low, so it's useful for the operator to be aware of this. The operator should be aware in any case so they can know to charge the robot.

**Comment by byao1459** [comment]
This issue on the web interface side has been resolved in this commit:
https://github.com/hcrlab/stretch_web_interface/commit/818a8ff6f27249d431f5a9d796777d96526fd49d

**Comment by nickswalker** [comment]
Excellent!
