### ISSUE TITLE
Stretch Gazebo Simulation

### ISSUE THREAD

**Issue by KaviMD** [hcrlab/stretch_web_interface#8]
Following the [instructions from PickNik](https://github.com/PickNikRobotics/stretch_ros/tree/pr-noetic_gazebo/stretch_gazebo), I'm working on getting stretch setup in gazebo. The worked out of the box for the most part, but there were a few things I had to change. First, gazebo was looking for some PID values to go with the joint trajectory controller, so I added some default ones.

The problem I'm currently stuck on affects both gazebo and rviz. There seems to be some missing joint transform info. Gazebo complains that
`[ERROR] [1624378932.416011656, 126.346000000]: Ignoring transform for child_frame_id "link_arm_l3" from authority "unknown_publisher" because of a nan value in the transform (nan nan nan) (0.000000 0.000000 -0.000000 1.000000)`

and rviz has this error that there is `No transform from [link_arm_l3] to [odom]`. (`link_arm_l3` in both errors is just a placeholder, the errors exist for many different joints)

Gazebo has a separate error: `[ERROR] [1624379155.998030257, 0.089000000]: GetModelState: model [robot] does not exist`, but then it displays the robot correctly in the 3d view, so I'm not fully sure what is going on.

Looking at the viewports in rviz and gazebo, it seems like all the objects that are missing transforms are currently at the origin, and (in rviz) have no texture, so there may be a deeper issue that I'm running into.
![image](https://user-images.githubusercontent.com/16945761/122963577-3fb09380-d33b-11eb-9b5d-ed607b47a76a.png)
Gazebo:
![image](https://user-images.githubusercontent.com/16945761/122964048-b9488180-d33b-11eb-8411-2f760558112a.png)

**Comment by KaviMD** [comment]
I re-setup everything with a new virutal machine running ubuntu 18 with the [pr-noetic-gazebo branch](https://github.com/PickNikRobotics/stretch_ros/tree/pr-noetic_gazebo/stretch_gazebo), and ROS melodic and now most of the errors are gone, gripper is in the right place, etc.

I'm working getting the camera feed visible in the the web interface, and the buttons in the web interface working with gazebo to move stretch. I've created a new branch for the [camera following and gazebo sim](https://github.com/hcrlab/stretch_web_interface/tree/gazebo_sim)

**Comment by KaviMD** [comment]
I was able to successfully get the gazebo camera view into the web interface! https://youtu.be/O1gkiOTxutI

The topic names from gazebo are different than the topic names from the robot
Gazebo: `/realsense/color/image_raw/compressed`, Robot: `/camera/color/image_raw/compressed`

Gazebo: `/joint_states`, Robot: `/stretch/joint_states/`

The `follow_joint_trajectory` is more complex, because on the robot, it is one topic, but in gazebo there are 4 different ones (head, body, arm, gripper).

I'm working on an update to the interface, so that it defaults to all of the robot ros paths, but that it is possible to switch to the gazebo ros paths. (I'm planning on doing this using local storage, but there may be a better way)

For reference this is the rqt_graph of the gazebo sim
![image](https://user-images.githubusercontent.com/16945761/123167433-5e8e5300-d42b-11eb-9c05-ee08c9884eaa.png)

**Comment by mayacakmak** [comment]
Ah okay, you had something even better here ;) so joint_states was empty?

**Comment by mayacakmak** [comment]
Awesome that you're able to test things with the Gazebo simulator now, that is super useful. Saw the video, that's a very empty world, hard to test the camera, but you succeeded 🤣

**Comment by mayacakmak** [comment]
@KaviMD when you have a chance can you paste the instructions for getting things working with the simulator, that you sent to @monalisa219 here also. Might be useful for others ;) thanks!

**Comment by KaviMD** [comment]
### Setup Instructions

I set everything up with Ubuntu 18.04 and ROS Melodic, but it should theoretically work with 20.04 and noetic.
Next, I downloaded and followed the setup instructions for the pr-noetic-gazebo branch of the [PickNik Stretch repo](https://github.com/PickNikRobotics/stretch_ros/tree/pr-noetic_gazebo/stretch_gazebo). This should at some point work with [hello-robot/stretch_ros](https://github.com/hello-robot/stretch_ros), but I'm not sure if it's fully up to date right now.

In addition to the setup instructions on github, I found that it was also necessary to run the `stretch_ros/stretch_description/urdf/xacro_to_urdf.sh` script, to create a placeholder urdf that the driver code wants.

I also commented out the `robot_state_publisher_node` in the `stretch_ros/stretch_core/launch/stretch_driver.launch` file (this is started automatically by the web interface). If this is uncommented, both it and gazebo publish robot data that causes rviz to flip between the two states.

Finally, because I set everything up with python 2,  I had to change the python path in the first line of `stretch_ros/stretch_gazebo/scripts/publish_ground_truth_odom.py`. to `#! /usr/bin/env python`
I think that is all the custom modifications I had to do to the stretch_ros code.

The instructions for the [web interface](https://github.com/hcrlab/stretch_web_interface) should work for setting up the web interface in sim and on the robot.

Once everything is setup, gazebo can be started with this command: `roslaunch stretch_gazebo gazebo.launch rviz:=true`, and the web interface with these commands. Make sure to start the web interface after gazebo is fully launched, or there will be a lot of errors.

### Notes
- I was able to get everything setup with ros noetic and ubuntu 20.04, and hello-robot/stretch_ros(there were a few issues with getting mongodb setup, but no modifications to the sim instructions)
- It would be good to add a sim flag to the `stretch_driver.launch` file, so that anyone using the sim doesn't have to comment out  `robot_state_publisher`
- Currently, the web interface installation script is only setup to use ubuntu 18.04 and ros melodic. I'm not sure if ros noetic is officially supported by hello robot, but if it is it would probably be good to update the installation script

**Comment by nickswalker** [comment]
We've since hacked together [a simulation](https://github.com/hcrlab/hcrl_gazebo) that's close enough to the robot to be useful for many interface development tasks (it depends on our fork of [stretch_ros](https://github.com/hcrlab/stretch_ros) as well). It does a fair job simulating the three cameras and provides a movement interface that is compatible with `stretch_ros` APIs.
![default_gzclient_camera(1)-2022-05-02T16_18_28 063929](https://user-images.githubusercontent.com/924295/166341386-025311e8-9382-40b5-b41b-996529b06782.jpg)
